/*********************************************************************************************************
** (C) Copyright 2002-2003 Christophe Calmejane, Thierry Carrard, Claude Limousin and Alexis Vartanian   
** All Rights Reserved.
**
** This is UNPUBLISHED PROPRIETARY SOURCE CODE of the authors ;
** the contents of this file may not be used, disclosed to third parties, 
** copied or duplicated in any form, in whole or in part, without the 
** prior written permission of the authors 
**********************************************************************************************************/
/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_SkyUtils_Console (void);
GtkWidget* create_ErrorWnd (void);
GtkWidget* create_ConfigWnd (void);
