/*********************************************************************************************************
** (C) Copyright 2002-2003 Christophe Calmejane, Thierry Carrard, Claude Limousin and Alexis Vartanian   
** All Rights Reserved.
**
** This is UNPUBLISHED PROPRIETARY SOURCE CODE of the authors ;
** the contents of this file may not be used, disclosed to third parties, 
** copied or duplicated in any form, in whole or in part, without the 
** prior written permission of the authors 
**********************************************************************************************************/
/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_SkyUtils_Console (void)
{
  GtkWidget *SkyUtils_Console;
  GtkWidget *vbox1;
  GtkWidget *scrolledwindow1;
  GtkWidget *textview1;
  GtkWidget *hbox1;
  GtkWidget *button1;
  GtkWidget *alignment2;
  GtkWidget *hbox3;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *button2;
  GtkWidget *alignment1;
  GtkWidget *hbox2;
  GtkWidget *image1;
  GtkWidget *label1;

  SkyUtils_Console = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (SkyUtils_Console, 200, 100);
  gtk_window_set_title (GTK_WINDOW (SkyUtils_Console), _("SkyUtils Console"));
  gtk_window_set_default_size (GTK_WINDOW (SkyUtils_Console), 500, 300);

  vbox1 = gtk_vbox_new (FALSE, 4);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (SkyUtils_Console), vbox1);
  gtk_container_set_border_width (GTK_CONTAINER (vbox1), 4);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), textview1);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textview1), FALSE);
  gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW (textview1), FALSE);

  hbox1 = gtk_hbox_new (TRUE, 16);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, FALSE, 4);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_box_pack_start (GTK_BOX (hbox1), button1, FALSE, FALSE, 0);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button1), alignment2);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox3);

  image2 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox3), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Cl_ear"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox3), label2, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_LEFT);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_box_pack_start (GTK_BOX (hbox1), button2, FALSE, FALSE, 0);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button2), alignment1);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox2);

  image1 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox2), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("_Config"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox2), label1, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_LEFT);

  g_signal_connect ((gpointer) SkyUtils_Console, "delete_event",
                    G_CALLBACK (on_SkyUtils_Console_delete_event),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (SkyUtils_Console, SkyUtils_Console, "SkyUtils_Console");
  GLADE_HOOKUP_OBJECT (SkyUtils_Console, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (SkyUtils_Console, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (SkyUtils_Console, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (SkyUtils_Console, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (SkyUtils_Console, button1, "button1");
  GLADE_HOOKUP_OBJECT (SkyUtils_Console, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (SkyUtils_Console, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (SkyUtils_Console, image2, "image2");
  GLADE_HOOKUP_OBJECT (SkyUtils_Console, label2, "label2");
  GLADE_HOOKUP_OBJECT (SkyUtils_Console, button2, "button2");
  GLADE_HOOKUP_OBJECT (SkyUtils_Console, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (SkyUtils_Console, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (SkyUtils_Console, image1, "image1");
  GLADE_HOOKUP_OBJECT (SkyUtils_Console, label1, "label1");

  return SkyUtils_Console;
}

GtkWidget*
create_ErrorWnd (void)
{
  GtkWidget *ErrorWnd;
  GtkWidget *fixed1;
  GtkWidget *image3;
  GtkWidget *button3;
  GtkWidget *label4;

  ErrorWnd = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ErrorWnd), _("SkyUtils Console Error"));
  gtk_window_set_position (GTK_WINDOW (ErrorWnd), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (ErrorWnd), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (ErrorWnd), FALSE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (ErrorWnd), TRUE);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (ErrorWnd), fixed1);
  gtk_container_set_border_width (GTK_CONTAINER (fixed1), 10);

  image3 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_fixed_put (GTK_FIXED (fixed1), image3, 24, 16);
  gtk_widget_set_size_request (image3, 40, 37);

  button3 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1), button3, 104, 80);
  gtk_widget_set_size_request (button3, 64, 24);

  label4 = gtk_label_new ("");
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 72, 0);
  gtk_widget_set_size_request (label4, 184, 72);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_FILL);
  gtk_label_set_line_wrap (GTK_LABEL (label4), TRUE);

  g_signal_connect ((gpointer) ErrorWnd, "delete_event",
                    G_CALLBACK (on_ErrorWnd_delete_event),
                    NULL);
  g_signal_connect_swapped ((gpointer) button3, "clicked",
                            G_CALLBACK (on_button3_clicked),
                            GTK_OBJECT (ErrorWnd));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ErrorWnd, ErrorWnd, "ErrorWnd");
  GLADE_HOOKUP_OBJECT (ErrorWnd, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ErrorWnd, image3, "image3");
  GLADE_HOOKUP_OBJECT (ErrorWnd, button3, "button3");
  GLADE_HOOKUP_OBJECT (ErrorWnd, label4, "label4");

  return ErrorWnd;
}

GtkWidget*
create_ConfigWnd (void)
{
  GtkWidget *ConfigWnd;
  GtkWidget *table1;
  GtkWidget *checkbutton2;
  GtkWidget *checkbutton3;
  GtkWidget *checkbutton4;
  GtkWidget *checkbutton5;
  GtkWidget *checkbutton6;
  GtkWidget *checkbutton7;
  GtkWidget *checkbutton8;
  GtkWidget *checkbutton9;
  GtkWidget *checkbutton10;
  GtkWidget *checkbutton11;
  GtkWidget *checkbutton12;
  GtkWidget *button4;
  GtkWidget *alignment3;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label5;
  GtkWidget *checkbutton1;

  ConfigWnd = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ConfigWnd), _("Configuration"));
  gtk_window_set_position (GTK_WINDOW (ConfigWnd), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (ConfigWnd), FALSE);

  table1 = gtk_table_new (7, 3, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (ConfigWnd), table1);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 6);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("Message 0x00002"));
  gtk_widget_show (checkbutton2);
  gtk_table_attach (GTK_TABLE (table1), checkbutton2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton2), 6);

  checkbutton3 = gtk_check_button_new_with_mnemonic (_("Message 0x00004"));
  gtk_widget_show (checkbutton3);
  gtk_table_attach (GTK_TABLE (table1), checkbutton3, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton3), 6);

  checkbutton4 = gtk_check_button_new_with_mnemonic (_("Message 0x00008"));
  gtk_widget_show (checkbutton4);
  gtk_table_attach (GTK_TABLE (table1), checkbutton4, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton4), 6);

  checkbutton5 = gtk_check_button_new_with_mnemonic (_("Message 0x00010"));
  gtk_widget_show (checkbutton5);
  gtk_table_attach (GTK_TABLE (table1), checkbutton5, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton5), 6);

  checkbutton6 = gtk_check_button_new_with_mnemonic (_("Message 0x00020"));
  gtk_widget_show (checkbutton6);
  gtk_table_attach (GTK_TABLE (table1), checkbutton6, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton6), 6);

  checkbutton7 = gtk_check_button_new_with_mnemonic (_("Message 0x00040"));
  gtk_widget_show (checkbutton7);
  gtk_table_attach (GTK_TABLE (table1), checkbutton7, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton8 = gtk_check_button_new_with_mnemonic (_("Message 0x00080"));
  gtk_widget_show (checkbutton8);
  gtk_table_attach (GTK_TABLE (table1), checkbutton8, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton9 = gtk_check_button_new_with_mnemonic (_("Message 0x00100"));
  gtk_widget_show (checkbutton9);
  gtk_table_attach (GTK_TABLE (table1), checkbutton9, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton10 = gtk_check_button_new_with_mnemonic (_("Message 0x00200"));
  gtk_widget_show (checkbutton10);
  gtk_table_attach (GTK_TABLE (table1), checkbutton10, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton11 = gtk_check_button_new_with_mnemonic (_("Message 0x00400"));
  gtk_widget_show (checkbutton11);
  gtk_table_attach (GTK_TABLE (table1), checkbutton11, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton12 = gtk_check_button_new_with_mnemonic (_("Message 0x00800"));
  gtk_widget_show (checkbutton12);
  gtk_table_attach (GTK_TABLE (table1), checkbutton12, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_table_attach (GTK_TABLE (table1), button4, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button4), alignment3);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("_Close"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("Message 0x00001"));
  gtk_widget_show (checkbutton1);
  gtk_table_attach (GTK_TABLE (table1), checkbutton1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton1), 6);

  g_signal_connect ((gpointer) ConfigWnd, "delete_event",
                    G_CALLBACK (on_ConfigWnd_delete_event),
                    NULL);
  g_signal_connect_swapped ((gpointer) button4, "clicked",
                            G_CALLBACK (on_button4_clicked),
                            GTK_OBJECT (ConfigWnd));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ConfigWnd, ConfigWnd, "ConfigWnd");
  GLADE_HOOKUP_OBJECT (ConfigWnd, table1, "table1");
  GLADE_HOOKUP_OBJECT (ConfigWnd, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (ConfigWnd, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (ConfigWnd, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (ConfigWnd, checkbutton5, "checkbutton5");
  GLADE_HOOKUP_OBJECT (ConfigWnd, checkbutton6, "checkbutton6");
  GLADE_HOOKUP_OBJECT (ConfigWnd, checkbutton7, "checkbutton7");
  GLADE_HOOKUP_OBJECT (ConfigWnd, checkbutton8, "checkbutton8");
  GLADE_HOOKUP_OBJECT (ConfigWnd, checkbutton9, "checkbutton9");
  GLADE_HOOKUP_OBJECT (ConfigWnd, checkbutton10, "checkbutton10");
  GLADE_HOOKUP_OBJECT (ConfigWnd, checkbutton11, "checkbutton11");
  GLADE_HOOKUP_OBJECT (ConfigWnd, checkbutton12, "checkbutton12");
  GLADE_HOOKUP_OBJECT (ConfigWnd, button4, "button4");
  GLADE_HOOKUP_OBJECT (ConfigWnd, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (ConfigWnd, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (ConfigWnd, image4, "image4");
  GLADE_HOOKUP_OBJECT (ConfigWnd, label5, "label5");
  GLADE_HOOKUP_OBJECT (ConfigWnd, checkbutton1, "checkbutton1");

  return ConfigWnd;
}

